# Generated by Django 4.2 on 2023-07-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_nome', models.CharField(max_length=50, verbose_name='Primeiro nome')),
                ('ultimo_nome', models.CharField(max_length=50, verbose_name='Ultimo nome')),
                ('Description', models.TextField(blank=True)),
                ('show', models.BooleanField(default=False)),
                ('picture', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
