# Generated by Django 4.2 on 2023-07-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Description',
            new_name='description',
        ),
        migrations.AddField(
            model_name='contact',
            name='celular',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='teste@teste.com', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='ultimo_nome',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ultimo nome'),
        ),
    ]
